import {
  boolean,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

import {
  changeFrequencyEnum,
  languageEnum,
  layoutDensityEnum,
  securityLevelEnum,
  themeEnum,
  twitterCardTypeEnum,
} from "./enums";

export const settings = pgTable(
  "settings",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    siteName: text("site_name").notNull(),
    siteDescription: text("site_description"),
    siteUrl: text("site_url").notNull(),
    defaultLanguage: languageEnum("default_language").notNull().default("uk"),
    supportedLanguages: text("supported_languages").array().notNull().default(["uk", "en"]),
    fallbackLanguage: languageEnum("fallback_language").notNull().default("uk"),
    automaticLocaleDetection: boolean("automatic_locale_detection").notNull().default(false),
    browserLanguageDetection: boolean("browser_language_detection").notNull().default(true),
    languageSwitcherEnabled: boolean("language_switcher_enabled").notNull().default(true),
    localizedUrlsEnabled: boolean("localized_urls_enabled").notNull().default(true),
    rtlSupportEnabled: boolean("rtl_support_enabled").notNull().default(false),
    securityLevel: securityLevelEnum("security_level").notNull().default("standard"),
    sessionIdleTimeoutHours: integer("session_idle_timeout_hours").notNull().default(8),
    sessionAbsoluteLifetimeHours: integer("session_absolute_lifetime_hours").notNull().default(24),
    loginLockoutEnabled: boolean("login_lockout_enabled").notNull().default(true),
    loginMaxAttempts: integer("login_max_attempts").notNull().default(5),
    loginLockoutWindowMinutes: integer("login_lockout_window_minutes").notNull().default(15),
    rateLimitSettingsPerMinute: integer("rate_limit_settings_per_minute").notNull().default(20),
    rateLimitUploadPerMinute: integer("rate_limit_upload_per_minute").notNull().default(30),
    rateLimitApiPerMinute: integer("rate_limit_api_per_minute").notNull().default(100),
    rateLimitSearchPerMinute: integer("rate_limit_search_per_minute").notNull().default(60),
    rateLimitImportPerMinute: integer("rate_limit_import_per_minute").notNull().default(10),
    rateLimitExportPerMinute: integer("rate_limit_export_per_minute").notNull().default(10),
    webhookMaxRetries: integer("webhook_max_retries").notNull().default(5),
    webhookRetryBaseDelaySeconds: integer("webhook_retry_base_delay_seconds").notNull().default(60),
    auditLogLoginEnabled: boolean("audit_log_login_enabled").notNull().default(true),
    auditLogFailedLoginEnabled: boolean("audit_log_failed_login_enabled").notNull().default(true),
    auditLogSettingsChangeEnabled: boolean("audit_log_settings_change_enabled").notNull().default(true),
    auditLogMediaUploadEnabled: boolean("audit_log_media_upload_enabled").notNull().default(true),
    auditLogSeoChangeEnabled: boolean("audit_log_seo_change_enabled").notNull().default(true),
    ipAllowList: text("ip_allow_list").array().notNull().default([]),
    ipBlockList: text("ip_block_list").array().notNull().default([]),
    timezone: text("timezone").notNull().default("Europe/Kyiv"),
    currency: text("currency").notNull().default("UAH"),
    logoUrl: text("logo_url"),
    faviconUrl: text("favicon_url"),
    defaultMetaTitle: text("default_meta_title"),
    defaultMetaDescription: text("default_meta_description"),
    defaultOgImage: text("default_og_image"),
    defaultTwitterCard: twitterCardTypeEnum("default_twitter_card").default("summary_large_image"),
    defaultIndexing: boolean("default_indexing").notNull().default(true),
    defaultFollow: boolean("default_follow").notNull().default(true),
    defaultRobots: text("default_robots").notNull().default("index, follow"),
    sitemapEnabled: boolean("sitemap_enabled").notNull().default(true),
    sitemapAutoGenerate: boolean("sitemap_auto_generate").notNull().default(true),
    sitemapUpdateFrequency: changeFrequencyEnum("sitemap_update_frequency").default("daily"),
    sitemapIncludeImages: boolean("sitemap_include_images").notNull().default(true),
    sitemapIncludeVideos: boolean("sitemap_include_videos").notNull().default(false),
    robotsEnabled: boolean("robots_enabled").notNull().default(true),
    robotsContent: text("robots_content"),
    theme: themeEnum("theme").notNull().default("system"),
    primaryColor: text("primary_color"),
    borderRadius: integer("border_radius").notNull().default(8),
    layoutDensity: layoutDensityEnum("layout_density").notNull().default("comfortable"),
    headScripts: text("head_scripts"),
    bodyScripts: text("body_scripts"),
    footerScripts: text("footer_scripts"),
    allowCustomScripts: boolean("allow_custom_scripts").notNull().default(false),
    googleAnalyticsId: text("google_analytics_id"),
    googleTagManagerId: text("google_tag_manager_id"),
    googleSearchConsoleVerification: text("google_search_console_verification"),
    bingWebmasterVerification: text("bing_webmaster_verification"),
    facebookPixelId: text("facebook_pixel_id"),
    maintenanceMode: boolean("maintenance_mode").notNull().default(false),
    debugMode: boolean("debug_mode").notNull().default(false),
    cacheEnabled: boolean("cache_enabled").notNull().default(true),
    seoAutomationEnabled: boolean("seo_automation_enabled").notNull().default(true),
    autoGenerateSchemas: boolean("auto_generate_schemas").notNull().default(true),
    autoGenerateMetadata: boolean("auto_generate_metadata").notNull().default(true),
    developerModeEnabled: boolean("developer_mode_enabled").notNull().default(false),
    showSqlQueries: boolean("show_sql_queries").notNull().default(false),
    showApiTiming: boolean("show_api_timing").notNull().default(false),
    showServerActions: boolean("show_server_actions").notNull().default(false),
    mockDataEnabled: boolean("mock_data_enabled").notNull().default(false),
    testModeEnabled: boolean("test_mode_enabled").notNull().default(false),
    developerToolbarEnabled: boolean("developer_toolbar_enabled").notNull().default(false),
    verboseLoggingEnabled: boolean("verbose_logging_enabled").notNull().default(false),
    backupScheduleEnabled: boolean("backup_schedule_enabled").notNull().default(false),
    backupScheduleHourUtc: integer("backup_schedule_hour_utc").notNull().default(3),
    backupRetentionMaxCount: integer("backup_retention_max_count").notNull().default(30),
    backupEncryptionEnabled: boolean("backup_encryption_enabled").notNull().default(true),
    storageProvider: text("storage_provider").notNull().default("supabase"),
    maxUploadSizeMb: integer("max_upload_size_mb").notNull().default(25),
    imageCompressionEnabled: boolean("image_compression_enabled").notNull().default(true),
    imageCompressionQuality: integer("image_compression_quality").notNull().default(80),
    autoWebpConversion: boolean("auto_webp_conversion").notNull().default(true),
    duplicateDetectionEnabled: boolean("duplicate_detection_enabled").notNull().default(true),
    smtpHost: text("smtp_host"),
    smtpPort: integer("smtp_port").notNull().default(587),
    smtpUsername: text("smtp_username"),
    smtpPasswordEncrypted: text("smtp_password_encrypted"),
    smtpEncryption: text("smtp_encryption").notNull().default("tls"),
    emailSenderName: text("email_sender_name"),
    emailSenderAddress: text("email_sender_address"),
    emailReplyTo: text("email_reply_to"),
    cacheDurationSeconds: integer("cache_duration_seconds").notNull().default(3600),
    cacheAutoCleanup: boolean("cache_auto_cleanup").notNull().default(true),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [index("settings_site_name_idx").on(table.siteName)],
);
