import type { SupportedLanguage } from "@/schemas/settings/settingsSchemas";

export interface SettingsRecord {
  readonly id: string;
  readonly siteName: string;
  readonly siteDescription: string | null;
  readonly siteUrl: string;
  readonly defaultLanguage: SupportedLanguage;
  readonly supportedLanguages: SupportedLanguage[];
  readonly fallbackLanguage: SupportedLanguage;
  readonly automaticLocaleDetection: boolean;
  readonly browserLanguageDetection: boolean;
  readonly languageSwitcherEnabled: boolean;
  readonly localizedUrlsEnabled: boolean;
  readonly rtlSupportEnabled: boolean;
  readonly securityLevel: "standard" | "enhanced" | "enterprise";
  readonly sessionIdleTimeoutHours: number;
  readonly sessionAbsoluteLifetimeHours: number;
  readonly loginLockoutEnabled: boolean;
  readonly loginMaxAttempts: number;
  readonly loginLockoutWindowMinutes: number;
  readonly rateLimitSettingsPerMinute: number;
  readonly rateLimitUploadPerMinute: number;
  readonly rateLimitApiPerMinute: number;
  readonly rateLimitSearchPerMinute: number;
  readonly rateLimitImportPerMinute: number;
  readonly rateLimitExportPerMinute: number;
  readonly webhookMaxRetries: number;
  readonly webhookRetryBaseDelaySeconds: number;
  readonly auditLogLoginEnabled: boolean;
  readonly auditLogFailedLoginEnabled: boolean;
  readonly auditLogSettingsChangeEnabled: boolean;
  readonly auditLogMediaUploadEnabled: boolean;
  readonly auditLogSeoChangeEnabled: boolean;
  readonly ipAllowList: readonly string[];
  readonly ipBlockList: readonly string[];
  readonly timezone: string;
  readonly currency: string;
  readonly logoUrl: string | null;
  readonly faviconUrl: string | null;
  readonly defaultMetaTitle: string | null;
  readonly defaultMetaDescription: string | null;
  readonly defaultOgImage: string | null;
  readonly defaultTwitterCard: "summary" | "summary_large_image" | null;
  readonly defaultIndexing: boolean;
  readonly defaultFollow: boolean;
  readonly defaultRobots: string;
  readonly sitemapEnabled: boolean;
  readonly sitemapAutoGenerate: boolean;
  readonly sitemapUpdateFrequency: "hourly" | "daily" | "weekly" | "monthly" | null;
  readonly sitemapIncludeImages: boolean;
  readonly sitemapIncludeVideos: boolean;
  readonly robotsEnabled: boolean;
  readonly robotsContent: string | null;
  readonly theme: "light" | "dark" | "system";
  readonly primaryColor: string | null;
  readonly borderRadius: number;
  readonly layoutDensity: "compact" | "comfortable";
  readonly headScripts: string | null;
  readonly bodyScripts: string | null;
  readonly footerScripts: string | null;
  readonly allowCustomScripts: boolean;
  readonly googleAnalyticsId: string | null;
  readonly googleTagManagerId: string | null;
  readonly googleSearchConsoleVerification: string | null;
  readonly bingWebmasterVerification: string | null;
  readonly facebookPixelId: string | null;
  readonly maintenanceMode: boolean;
  readonly debugMode: boolean;
  readonly cacheEnabled: boolean;
  readonly seoAutomationEnabled: boolean;
  readonly autoGenerateSchemas: boolean;
  readonly autoGenerateMetadata: boolean;
  readonly developerModeEnabled: boolean;
  readonly showSqlQueries: boolean;
  readonly showApiTiming: boolean;
  readonly showServerActions: boolean;
  readonly mockDataEnabled: boolean;
  readonly testModeEnabled: boolean;
  readonly developerToolbarEnabled: boolean;
  readonly verboseLoggingEnabled: boolean;
  readonly backupScheduleEnabled: boolean;
  readonly backupScheduleHourUtc: number;
  readonly backupRetentionMaxCount: number;
  readonly backupEncryptionEnabled: boolean;
  readonly storageProvider: "supabase";
  readonly maxUploadSizeMb: number;
  readonly imageCompressionEnabled: boolean;
  readonly imageCompressionQuality: number;
  readonly autoWebpConversion: boolean;
  readonly duplicateDetectionEnabled: boolean;
  readonly smtpHost: string | null;
  readonly smtpPort: number;
  readonly smtpUsername: string | null;
  readonly smtpPasswordEncrypted: string | null;
  readonly smtpEncryption: "tls" | "ssl" | "none";
  readonly emailSenderName: string | null;
  readonly emailSenderAddress: string | null;
  readonly emailReplyTo: string | null;
  readonly cacheDurationSeconds: number;
  readonly cacheAutoCleanup: boolean;
  readonly updatedAt: Date;
}
